POST http://localhost:3000/products
content-type: application/json

{
  "name": "Tuna 8",
  "description": "canned fish",
  "price": "1000",
  "status": "DRAFT"
}

###
PATCH http://localhost:3000/products/6
content-type: application/json

{
  "name": "Tuna 3",
  "description": "canned fish 3",
  "price": "1300"
}

###
PATCH http://localhost:3000/products/5/status
content-type: application/json

{
  "status": "PUBLISHED"
}

###
GET http://localhost:3000/products/56789
content-type: application/json

###
GET http://localhost:3000/products/5
content-type: application/json

###
GET http://localhost:3000/products?status=DRAFT
content-type: application/json

###
GET http://localhost:3000/products?search=randomtext
content-type: application/json

###
GET http://localhost:3000/products?search=Tuna
content-type: application/json

###
GET http://localhost:3000/products?status=COMPLETED
content-type: application/json

###
GET http://localhost:3000/products
content-type: application/json

###
DELETE  http://localhost:3000/products/5
content-type: application/json